version: "3"

services:
  php-app2:
    build:
      context: ./backend
      dockerfile: DockerfileDev
    restart: unless-stopped
    networks:
      - default

  nginx-app2:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - php-app2
    expose:
      - "80"
    networks:
      - default